name: Test and build package

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install and run pre-commit via tox
      run: |
        python -m pip install --upgrade tox tox-gh-actions
        python -m tox
